# Generated by Django 5.0.6 on 2024-07-03 10:51

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('customer_type', models.PositiveSmallIntegerField(choices=[(1, 'Dealer'), (2, 'Homeowner')])),
                ('fbid', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip_code', models.CharField(default='00000', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('owner_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('medallion', models.BooleanField(default=False)),
                ('current_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_dealer_profile', to=settings.AUTH_USER_MODEL)),
                ('previous_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
