# Generated by Django 5.0.6 on 2024-07-05 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('rm_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_entered', models.DateField()),
                ('service_date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed')], default=0)),
                ('status_code', models.SmallIntegerField(choices=[(100, 'Initial Review'), (200, 'Under Review'), (300, 'Approved'), (400, 'Rejected')])),
                ('date_finalized', models.DateField(blank=True, null=True)),
                ('csr_note', models.TextField(blank=True, null=True)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('dealer_ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('claim_action', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Repair'), (2, 'replace')], null=True)),
                ('part_problem', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Freeze Damage'), (2, 'Dimple Leak - Rev Only'), (3, 'Header Leak'), (4, 'Panel Leak'), (5, 'Panel Split'), (6, 'Panel too long'), (7, 'Panel too short'), (8, 'VRV Fail')], null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='claim_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claim.claim')),
            ],
        ),
    ]
