# Generated by Django 5.0.6 on 2024-07-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claim_action',
        ),
    ]
