# Generated by Django 5.0.6 on 2024-07-08 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_remove_claim_claim_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='barcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Repair'), (2, 'replace')], null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_installed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
