# Generated by Django 5.0.6 on 2024-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_claim_active_claim_barcode_claim_claim_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
