# Generated by Django 5.0.6 on 2024-07-05 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=6)),
                ('part_description', models.CharField(max_length=255)),
                ('product_line', models.CharField(max_length=255)),
                ('date_installed', models.DateField()),
                ('barcode', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('problem_code', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Problem 1'), (2, 'Problem 2')], null=True)),
                ('installing_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
