# Generated by Django 5.0.6 on 2024-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partcsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('part_description', models.CharField(max_length=255)),
                ('product_line', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
