# Generated by Django 5.0.6 on 2024-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_partcsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='claim_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Repair'), (2, 'replace')], null=True),
        ),
    ]
