# Generated by Django 5.0.6 on 2024-07-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_part_claim_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='active',
        ),
        migrations.RemoveField(
            model_name='part',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='part',
            name='date_installed',
        ),
    ]
