# Generated by Django 5.0.6 on 2024-07-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0004_remove_part_active_remove_part_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='claim_action',
        ),
    ]
